# Generated by Django 4.0.2 on 2022-03-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=80, null=True)),
                ('body', models.TextField(blank=True, max_length=255, null=True)),
                ('mail_date', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[mail.models.file_size])),
                ('trash', models.BooleanField(default=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('send', 'send')], max_length=5, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('bcc', models.ManyToManyField(blank=True, related_name='bcc', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='mail.Category')),
                ('cc', models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(related_name='amail_receiver', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ManyToManyField(to='mail.Amail')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='amail_sender', to=settings.AUTH_USER_MODEL)),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.signature')),
            ],
        ),
    ]
