# Generated by Django 4.0.2 on 2022-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
