# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amail',
            name='category',
        ),
        migrations.AddField(
            model_name='amail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mail.category'),
        ),
    ]
