# Generated by Django 4.0.2 on 2022-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='filter',
            field=models.ManyToManyField(blank=True, to='mail.Filter'),
        ),
    ]
