# Generated by Django 4.0.2 on 2022-04-04 12:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_amail_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amail',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
