# Generated by Django 4.0.2 on 2022-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_amail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amail',
            name='category',
            field=models.ManyToManyField(blank=True, to='mail.Category'),
        ),
    ]
