# Generated by Django 4.0.2 on 2022-03-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_amail_bcc_alter_amail_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amail',
            name='reply',
        ),
        migrations.AddField(
            model_name='amail',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.amail'),
        ),
    ]
