# Generated by Django 4.0.2 on 2022-03-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0008_remove_amail_reply_amail_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('send', 'send')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amail',
            name='bcc',
            field=models.ManyToManyField(related_name='bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='amail',
            name='category',
        ),
        migrations.AddField(
            model_name='amail',
            name='category',
            field=models.ManyToManyField(to='mail.Category'),
        ),
        migrations.AlterField(
            model_name='amail',
            name='cc',
            field=models.ManyToManyField(related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
