# Generated by Django 4.0.2 on 2022-03-08 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0009_amail_status_category_owner_alter_amail_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amail',
            name='bcc',
            field=models.ManyToManyField(blank=True, related_name='bcc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='amail',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
